### ISSUE TITLE
Can you provide the demo to use the encrypted model?

### ISSUE THREAD

**Issue by CPFelix** [zhongqingyang/LibtorchModelEncryption#1]
I'm troubled about how to use the encrypted model in libtorch?Thank you for help!

**Comment by zhongqingyang** [comment]
I uploaded the encryption and decryption code, you can try them.

**Comment by CPFelix** [comment]
I had tred your shared codes, but when load the encrypted model, c10 Error appeared.
![](C:\Users\25789\Desktop\C240E95A-00F2-4f4b-B56B-215F4D3C1DCF.png)
And I have some questions about encrypting model: 
the encrypted model is not the same size with orgin model? When the encrypted char is **'\n'**,it seems has some troubles?

**Comment by zhongqingyang** [comment]
> 我曾尝试过使用您的共享代码，但是在加载加密模型时，出现c10错误。 我对加密模型有一些疑问：加密模型和原始 模型的大小不一样吗？当加密的字符为'\ n'时，似乎有麻烦吗？

When loading, you need to decrypt the model and convert it to istream, and then use torch:: JIT:: load（std::istream& in,c10::optional<c10::Device> device = c10::nullopt,ExtraFilesMap& extra_ files = default_ extra_ files);

**Comment by CPFelix** [comment]
I still get the c10 error and can't load the model successfully.This is my model decrypt and load code, can you help to find is there any mistakes?Thanks @zhongqingyang 


	try
	{
		if (modelKey.size() == 0)
		{
			module = torch::jit::load(modelFullPath.c_str());
		}
		else
		{
			char *buf = nullptr;
			FILE *file = fopen(modelFullPath.c_str(), "r");
			fseek(file, 0, SEEK_END);
			unsigned size = ftell(file);
			fseek(file, 0, SEEK_SET);
			buf = (char *)malloc(size);
			std::memset(buf, 0, size);
			unsigned int i = 0, j = 0;
			while (!feof(file))
			{
				char ch = (fgetc(file)) ^ (modelKey[i >= modelKey.length() ? i = 0 : i++]);
				buf[j++] = ch;
			}

			std::istringstream ss;
			ss.rdbuf()->pubsetbuf(buf, j - 1);
			module = torch::jit::load(ss);
		}
	}
	catch (const c10::Error &e)
	{
		std::cerr << "Error loading the Detect model!\n";
		std::cerr << "Model Path:" << modelFullPath << "\n";
		//std::exit(EXIT_FAILURE);
		system("Pause");
	}
	
	
	module.to(device_type); // 模型加载至GPU
	if (torch::cuda::is_available())
	{
		std::cout << "load Detect model in CUDA!" << std::endl;
	}
	else
	{
		std::cout << "load Detect model in CPU!" << std::endl;
	}
